# Use uma imagem base do Ubuntu com Python instalado
FROM python:3.9-slim

# Adicione o diretório de trabalho
WORKDIR /app

# Copie os arquivos necessários para o container
COPY . .

# Instale as dependências do Python
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Comando para executar o script
CMD ["python", "bot.py"]
