# Use uma imagem Python oficial como base
FROM python:3.9-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o conteúdo do diretório atual para o diretório de trabalho no contêiner
COPY . /app

# Copie o script de configuração para o contêiner
COPY setup_and_run.sh /app/setup_and_run.sh

# Torne o script executável
RUN chmod +x /app/setup_and_run.sh

# Execute o script de configuração
CMD ["/app/setup_and_run.sh"]
