version: "3.1"

services:
    postgresql:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        volumes:
            - /var/cache/postgres_data_2:/var/lib/postgresql/data


    fastapi:
        build: .
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - postgresql

