services:
  postgresql:
    image: postgres
    restart: always
    container_name: api_siad_postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/cache/postgres_data_2:/var/lib/postgresql/data

  fastapi:
    image: api_siad_fastapi
    restart: always
    container_name: api_siad_fastapi
    depends_on:
      - postgresql
    env_file:
      - .env
    expose:
      - "8000"
    environment:
      - DB_URL=postgresql+psycopg2://admin:adminpass@api_siad_postgresql:5432/railway

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - fastapi
    environment:
      SECRETCODE: ${SECRETCODE}
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    restart: always
    container_name: api_siad_nginx
    depends_on:
      - fastapi
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
