"""remove column user_id

Revision ID: 0124dd839dd6
Revises: 38f151f6a244
Create Date: 2024-04-03 19:50:53.518749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0124dd839dd6'
down_revision: Union[str, None] = '38f151f6a244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reseter_need_user_id_fkey', 'reseter_need', type_='foreignkey')
    op.drop_column('reseter_need', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reseter_need', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reseter_need_user_id_fkey', 'reseter_need', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
